TRUNCATE TABLE template;

INSERT INTO template (name, json) VALUES ('Muscle Workout Info', '[{"label": "운동 부위", "type": "text", "name": "bodypart", "value": "가슴", "placeholder": "신체 부위를 입력해주세요"}, {"label": "상세 부위", "type": "text", "name": "detailed bodypart", "value": "대흉근 하부", "placeholder": "상세 신체 부위를 입력해주세요"}, {"label": "질문", "type": "textline", "name": "question", "value": "근육을 키우기 위한 운동들을 알려줘", "placeholder": "질문을 입력해주세요"}, {"label": "답변", "type": "textline", "name": "answer", "value": "번호, 운동 이름, 횟수, 방법", "placeholder": "답변 양식을 입력해주세요"}]');
INSERT INTO template (name, json) VALUES ('Certification Info', '[{"label": "분야", "type": "text", "name": "field", "value": "컴퓨터", "placeholder": "분야를 입력해주세요"}, {"label": "경력", "type": "text", "name": "career", "value": "없음", "placeholder": "경력을 입력해주세요"}, {"label": "목적", "type": "text", "name": "purpose", "value": "취업을 위해", "placeholder": "목적을 입력해주세요"}, {"label": "질문", "type": "textline", "name": "question", "value": "취득하면 좋은 자격증을 알려줘", "placeholder": "질문을 입력해주세요"}, {"label": "답변", "type": "textline", "name": "answer", "value": "번호, 자격증 이름, 설명, 시험 정보", "placeholder": "답변 양식을 입력해주세요"}]');
INSERT INTO template (name, json) VALUES ('Movie Recommendation', '[{"label": "장르", "type": "text", "name": "genre", "value": "공포", "placeholder": "장르를 입력해주세요"}, {"label": "개봉 시기", "type": "text", "name": "release time", "value": "2023년 이후", "placeholder": "개봉 시기를 입력해주세요"}, {"label": "주제", "type": "text", "name": "theme", "value": "심리적 공포", "placeholder": "주제를 입력해주세요"}, {"label": "질문", "type": "textline", "name": "question", "value": "영화를 추천해줘", "placeholder": "질문을 입력해주세요"}, {"label": "답변", "type": "textline", "name": "answer", "value": "번호, 영화 제목, 감독, 주연 배우, 평점, 상영 시간", "placeholder": "답변 양식을 입력해주세요"}]');
INSERT INTO template (name, json) VALUES ('Historical Event Exploration', '[{"label": "시기", "type": "text", "name": "period", "value": "19세기", "placeholder": "시기를 입력해주세요"}, {"label": "지역", "type": "text", "name": "region", "value": "동아시아", "placeholder": "지역을 입력해주세요"}, {"label": "유형", "type": "text", "name": "category", "value": "외교적 사건", "placeholder": "유형을 입력해주세요"}, {"label": "질문", "type": "textline", "name": "question", "value": "어떤 역사적 사건이 있었는지 알려줘", "placeholder": "질문을 입력해주세요"}, {"label": "답변", "type": "textline", "name": "answer", "value": "번호, 사건 이름, 개요, 전개, 결과", "placeholder": "답변 양식을 입력해주세요"}]');
INSERT INTO template (name, json) VALUES ('Travel Planning', '[{"label": "기간", "type": "text", "name": "period", "value": "2024년 7월 17일 ~ 20일", "placeholder": "기간을 입력해주세요"}, {"label": "목적지", "type": "text", "name": "destination", "value": "일본 오사카", "placeholder": "목적지을 입력해주세요"}, {"label": "인원 수", "type": "text", "name": "number of people", "value": "3명", "placeholder": "인원 수를 입력해주세요"}, {"label": "예산", "type": "text", "name": "category", "value": "200만원", "placeholder": "예산을 입력해주세요"}, {"label": "질문", "type": "textline", "name": "question", "value": "여행 계획을 세워줘", "placeholder": "질문을 입력해주세요"}, {"label": "답변", "type": "textline", "name": "answer", "value": "번호, 일정, 숙박 정보, 교통 수단, 식사", "placeholder": "답변 양식을 입력해주세요"}]');
INSERT INTO template (name, json) VALUES ('Cooking Recipe Recommendation', '[{"label": "종류", "type": "text", "name": "type", "value": "메인 요리", "placeholder": "종류를 입력해주세요"}, {"label": "인원 수", "type": "text", "name": "number of people", "value": "6명", "placeholder": "인원 수를 입력해주세요"}, {"label": "목적", "type": "text", "name": "purpose", "value": "생일 파티", "placeholder": "목적을 입력해주세요"}, {"label": "질문", "type": "textline", "name": "question", "value": "요리 레시피를 알려줘", "placeholder": "질문을 입력해주세요"}, {"label": "답변", "type": "textline", "name": "answer", "value": "번호, 요리 이름, 재료, 도구, 시간, 방법", "placeholder": "답변 양식을 입력해주세요"}]');
INSERT INTO template (name, json) VALUES ('Music Recommendation', '[{"label": "장르", "type": "text", "name": "genre", "value": "밴드", "placeholder": "장르를 입력해주세요"}, {"label": "분위기", "type": "text", "name": "mood", "value": "여행을 가는 신나는 상황", "placeholder": "분위기를 입력해주세요"}, {"label": "언어", "type": "text", "name": "language", "value": "상관 없음", "placeholder": "언어를 입력해주세요"}, {"label": "질문", "type": "textline", "name": "question", "value": "음악을 추천해줘", "placeholder": "질문을 입력해주세요"}, {"label": "답변", "type": "textline", "name": "answer", "value": "번호, 음악 이름, 아티스트 이름, 발매 년도", "placeholder": "답변 양식을 입력해주세요"}]');
INSERT INTO template (name, json) VALUES ('Career Exploration', '[{"label": "분야", "type": "text", "name": "field", "value": "IT", "placeholder": "분야를 입력해주세요"}, {"label": "전공", "type": "text", "name": "major", "value": "컴퓨터 공학", "placeholder": "전공을 입력해주세요"}, {"label": "기술", "type": "textline", "name": "skill", "value": "프로그래밍 언어와 자격증", "placeholder": "기술을 입력해주세요"}, {"label": "질문", "type": "textline", "name": "question", "value": "진로를 추천해줘", "placeholder": "질문을 입력해주세요"}, {"label": "답변", "type": "textline", "name": "answer", "value": "번호, 직업 이름, 주요 업무, 필요 역량, 평균 연봉", "placeholder": "답변 양식을 입력해주세요"}]');
INSERT INTO template (name, json) VALUES ('Paper Research', '[{"label": "주제", "type": "text", "name": "theme", "value": "인공지능", "placeholder": "주제를 입력해주세요"}, {"label": "목적", "type": "text", "name": "purpose", "value": "전공 심화 공부", "placeholder": "목적을 입력해주세요"}, {"label": "키워드", "type": "text", "name": "keyword", "value": "맘바", "placeholder": "키워드를 입력해주세요"}, {"label": "질문", "type": "textline", "name": "question", "value": "최신 논문들을 찾아줘", "placeholder": "질문을 입력해주세요"}, {"label": "답변", "type": "textline", "name": "answer", "value": "번호, 논문 이름, 저자 이름, 출판 연도, 학술지 이름, 내용 요약", "placeholder": "답변 양식을 입력해주세요"}]');
INSERT INTO template (name, json) VALUES ('Welfare Service Exploration', '[{"label": "서비스 유형", "type": "text", "name": "service type", "value": "의료 지원", "placeholder": "서비스 유형을 입력해주세요"}, {"label": "대상", "type": "text", "name": "target", "value": "저소득층", "placeholder": "대상을 입력해주세요"}, {"label": "지원 내용", "type": "text", "name": "support", "value": "건강 검진", "placeholder": "지원 내용을 입력해주세요"}, {"label": "질문", "type": "textline", "name": "question", "value": "사용 가능한 복지 서비스를 알려줘", "placeholder": "질문을 입력해주세요"}, {"label": "답변", "type": "textline", "name": "answer", "value": "번호, 서비스 이름, 서비스 설명, 이용 조건", "placeholder": "답변 양식을 입력해주세요"}]');

commit;